### ISSUE TITLE
`no_std` support broken by crate num-prime

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-rs#1042]
commit a17875900d0514b144e26d56904dc90fe0bbea6e introduced a dependency to crate `num-prime`, which does not support `no_std` (it imports `num-bigin` without `default-features = false`)

This makes it impossible for Madara to depend on the last version of `cairo-vm` and `blockifier`.

I understand that you may not want to use `num-primes` instead because its `is_prime` method is [bugged](https://github.com/AtropineTears/num-primes#warning).

Do you think we can find a third alternative that both works and is `no_std` compatible?

After this I will try to find a way for the CI to fail if `no_std` support is broken in a way that is currently invisible to the current tests, but harmful to Madara

**Comment by Oppen** [comment]
Thanks for the heads up! Contact me via Telegram if you need to brainstorm how to get the CI to catch these issues, I've been working on the pipelines lately and I'm planning to tackle the robustness part soon.

I'll finish up some tasks on my own and try to find a solution to the particular problem. For a start I'll send `num-prime` a patch assuming it's easy enough to fix there.

**Comment by Oppen** [comment]
In retrospect, @fmoletta what do you think of just using the alternative `is_prime`? Since it's probabilistic anyway I think we're implicitly accepting some chance of accepting a non-prime or rejecting a prime. It doesn't make me happy that it's non-deterministic, but if it's the original behavior then we should be able to live with it.

**Comment by fmoletta** [comment]
> In retrospect, @fmoletta what do you think of just using the alternative `is_prime`? Since it's probabilistic anyway I think we're implicitly accepting some chance of accepting a non-prime or rejecting a prime. It doesn't make me happy that it's non-deterministic, but if it's the original behavior then we should be able to live with it.

`is_prime` imports `num-bigint` with default features too.  Or did you mean the `is_prime` provided by `num-primes`? Ill give it a try

**Comment by fmoletta** [comment]
> > In retrospect, @fmoletta what do you think of just using the alternative `is_prime`? Since it's probabilistic anyway I think we're implicitly accepting some chance of accepting a non-prime or rejecting a prime. It doesn't make me happy that it's non-deterministic, but if it's the original behavior then we should be able to live with it.
> 
> `is_prime` imports `num-bigint` with default features too. Or did you mean the `is_prime` provided by `num-primes`? Ill give it a try

Update: Its not passing our tests, it sometimes causes one test to panic

**Comment by tdelabro** [comment]
A way could be to fork `num-prime`, and make it support `no_std`. I don't think it will be an overwhelming amount of work. And it could be merged in the original crate afterward

**Comment by tdelabro** [comment]
What we did for now it an ugly copy paste of the is_prime method directly in cairo-vm. And we used `SmallRng` rather than the rng source that relly on `getrandom` (which is not compatible with substrate).

It's an ugly fix but it work and will allow us to compile until we find a better way

**Comment by pefontana** [comment]
Done [#1238](https://github.com/lambdaclass/cairo-rs/pull/1238)
