### ISSUE TITLE
Discuss and analyze webassembly security

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/cairo-rs#166]
WebAssembly does not protect against problems inside the sandbox. If you have C++ code that executed undefined behaviour, it can do any possible thing it likes inside that sandbox, poking the interface to the host in any possible way, but the full C++ UB experience does not transfer to the embedder. In that way it can be thought of like a mini-process in your process, or as a container for a library.

- https://www.oreilly.com/library/view/webassembly-the-definitive/9781492089834/ch04.html
- https://petermalmgren.com/serverside-wasm-data/
- https://youtu.be/glL__xjviro
- https://news.ycombinator.com/item?id=24216764
- https://mvolkmann.github.io/blog/webassembly/?v=1.0.19
- https://stackoverflow.com/questions/69789570/webassembly-thread-safety-and-c-c-local-variables
- https://stackoverflow.com/questions/64763007/why-is-webassembly-safe-and-what-is-linear-memory-model
- https://mvolkmann.github.io/blog/webassembly/?v=1.0.19
- https://wasmbyexample.dev/examples/webassembly-linear-memory/webassembly-linear-memory.rust.en-us.html
- https://hacks.mozilla.org/2019/08/webassembly-interface-types/

**Comment by unbalancedparentheses** [comment]
![](https://imgs.xkcd.com/comics/sandboxing_cycle_2x.png)

**Comment by pefontana** [comment]
We won't use wasm hints
