### ISSUE TITLE
Add a CLI option to specify the entrypoint

### ISSUE THREAD

**Issue by Bernardstanislas** [lambdaclass/cairo-rs#180]
Currently the entrypoint to the cairo file being run is [hardcoded](https://github.com/lambdaclass/cleopatra_cairo/blob/main/src/serde/deserialize_program.rs#L124) to the `main` function.
Since we'd like at Onlydust to leverage your VM to build a fast Cairo test runner, we would need to be able to specify a different entrypoint, let's say `my_function` for example.

I plan to work on this, I open the issue to start the conversation and get your point of view on this.

**Comment by unbalancedparentheses** [comment]
Hi, thanks for creating the issue. We are working on adding hints, as soon as we have it working we can add this. If you want to send a PR we can discuss it and merge it.
