### ISSUE TITLE
Either move to either Montgomery form or implement Barrett reductions

### ISSUE THREAD

**Issue by Oppen** [lambdaclass/cairo-rs#256]
A significant part of runtime is spent in performing modular arithmetic. These operations can be greatly optimized by using [Montgomery form](https://en.wikipedia.org/wiki/Montgomery_modular_multiplication) to represent our fields or by using [Barrett reduction](https://en.wikipedia.org/wiki/Barrett_reduction) to perform division.

**Comment by pefontana** [comment]
We will use lambdaworks
