### ISSUE TITLE
See if we can use fixed (or at least bounded) size representations

### ISSUE THREAD

**Issue by Oppen** [lambdaclass/cairo-rs#257]
Research whether there's a bound to the prime defining the field and use that to check whether we can use a smaller big integer implementation that can be allocated on the stack. For example, let's say our prime can't be greater than 2^128, our fields can be a single 128 bits int most of the time, 256 as temporary values during multiplication, as long as we always convert back into a valid field element.

**Comment by unbalancedparentheses** [comment]
Could you please explain this issue a little bit more to me? Thanks!

**Comment by Oppen** [comment]
Lots of our runtime is wasted on allocating big integers on the heap. This happens, in part, because the crate is meant for general usage where you truly have arbitrary sizes of integers, so you'd end up using a vector for the limbs. Our usage, on the contrary, is bounded. Memory slots in Cairo are 256 bits (I didn't know that at the time of writing the issue, but it applies anyway). As long as you keep stuff in range for a valid field, you'll use at most twice that size (multiplication can require twice the regular size for the bitfield temporarily). Considering we don't rely too much on recursion, those numbers on the stack wouldn't be a problem, and will save us all of our small allocations, specially those created as temporary variables during operation.

Now, this issue assumes we don't simply go with ark_ff, that already behaves like that. There are several crates where you can use bounded big integers, where "big" only means "not limited by the word size of the architecture" rather than "may have any number of digits".

**Comment by pefontana** [comment]
Not relevant after move to lambdawork
