### ISSUE TITLE
Abstract the representation of field elements

### ISSUE THREAD

**Issue by Oppen** [lambdaclass/cairo-rs#268]
We're currently using `BigInt` explicitly, which forces us to compute the `.mod_floor` of results after every operation, use costly divisions, etc.

The first step to fix arithmetic performance issues is to isolate the field properties into a new type and let the rest of the code operate on fields in a more abstract way.

**Comment by Oppen** [comment]
A quick test shows that if we could guarantee the field invariant holds between operations just removing the call to `.div_floor` after additions in `.add_int_mod` (it would, internally to the new type, become a conditional addition) can improve 10-15% execution speed in our benchmarks.

**Comment by igaray** [comment]
This is a good refactor to take on asap but after we finish the python hints
