### ISSUE TITLE
Implementing cairo-compile

### ISSUE THREAD

**Issue by Nashtare** [lambdaclass/cairo-rs#269]
Hi guys! 
Super cool work you're doing! I saw cleopatra was supporting only the equivalent of cairo-run at the moment. Do you envision supporting as well compilation of cairo programs in the future? Or do you intend to stay pegged to the toolchain (with the potential limitations it brings)?
Thanks!

**Comment by unbalancedparentheses** [comment]
Hi @Nashtare, thanks for the comment. Some news about this will be presented at StarkNet.CC in this front! I will update the issue after StarkNet.CC

**Comment by Nashtare** [comment]
Great! Looking forward, thanks! :)

**Comment by Nashtare** [comment]
@unbalancedparentheses Do you have any update on this? :)
