### ISSUE TITLE
Install deps should use pip3?

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/cairo-rs#310]
I am pretty sure the make deps is not working... we should be using pip3. Please correct me if I'm wrong
https://github.com/lambdaclass/cleopatra_cairo/blob/main/Makefile#L45-L48

**Comment by Oppen** [comment]
pip3 is a disambiguation in case both Python 2.7 and Python 3.x coexist, but pip is not necessarily for 2.7. With pyenv, pip is the one matching the pyenv currently active:
```shell
[pelito@pelito-x1 cleopatra_cairo]$ PYENV_VERSION=3.7.12 pip -V
pip 20.1.1 from /home/pelito/.pyenv/versions/3.7.12/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by Oppen** [comment]
Is it a Debian derivative? Is it using pyenv or calling pip directly?
Debian derivatives still ship Python 2.7 AFAIK and you need to install a package called something like `python-is-python3` for `python` and `pip` to point to version 3.x.

**Comment by pefontana** [comment]
we use pyenv
