### ISSUE TITLE
Offer a RPC devnet or local node wrapper for `cairo-rs`

### ISSUE THREAD

**Issue by 0xSidius** [lambdaclass/cairo-rs#426]
Would allow Rust developers to opt out of the current Python impl. of `starknet-devnet` which is a Flask wrapper for the standard Python Cairo VM

**Comment by 0xSidius** [comment]
@fmoletta hello, any plans for this?

**Comment by Oppen** [comment]
We're currently working on making cairo-rs embeddable in Python as a module, so it should be possible to write a Flask wrapper similar to that. There are currently no plans to do it, but I don't see any reason to reject PRs building that wrapper.
Is that what you were asking about?

**Comment by 0xSidius** [comment]
> We're currently working on making cairo-rs embeddable in Python as a module, so it should be possible to write a Flask wrapper similar to that. There are currently no plans to do it, but I don't see any reason to reject PRs building that wrapper. Is that what you were asking about?

Hi, yes it was thanks, but can you explain why we can't have a Rust-only stack in the future down the line?

**Comment by Oppen** [comment]
There's no stoppers for that. We're still stabilizing some interfaces so you won't yet find the crate in crates.io, but you can still import it with the repo path if you want. Note Python support will still be needed if you use hints outside of those in the standard library.
