### ISSUE TITLE
syscalls hints not implement

### ISSUE THREAD

**Issue by yp945** [lambdaclass/cairo-rs#498]
Hi, is the code not implementing the syscalls related hints yet?

<img width="985" alt="image" src="https://user-images.githubusercontent.com/15030378/197928080-1f4a7f45-25b7-452e-a893-478f29922b01.png">

**Comment by Juan-M-V** [comment]
Hi! we are currently working on https://github.com/lambdaclass/cairo-rs-py. With this we would start supporting all hints and starkware infrastructure
