### ISSUE TITLE
Support for new cairo-lang syntax

### ISSUE THREAD

**Issue by karol-bisztyga** [lambdaclass/cairo-rs#620]
Hey!
I understand that cairo-rs supports cairo-lang 0.9.1, right?
Since the output JSON files of compiled cairo contracts have changed in 0.10.0 it would be great to have support for it.

**Comment by unbalancedparentheses** [comment]
@karol-bisztyga Thanks for creating the issue. Sure this would be great. Do you want to send a PR for this or should we do it?

copying @HermanObst

**Comment by karol-bisztyga** [comment]
Hi! I put up a PR for this already https://github.com/lambdaclass/cairo-rs/pull/619
