### ISSUE TITLE
Inconsitent errors with python vm

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [lambdaclass/cairo-rs#638]
Original python-vm  raises a error thrown in hint,  cairo-rs dumps it to a plain string and raises `VmException`.

Example of `VMException`:
```
{'code': <StarknetErrorCode.TRANSACTION_FAILED: 44>, 'message': 'Error at pc=None:\nNone\nCustom Hint Error: SomeCustomError()', 'status_code': 500, 'body': {'code': <StarknetErrorCode.TRANSACTION_FAILED: 44>, 'message': 'Error at pc=None:\nNone\nCustom Hint Error: SomeCustomError()'}}
```

We can work this around in protostar using some pattern matching but i believe it is important part and huge inconsistency with the original vm.  It is possible to maybe pickle original exception and provide it in some  structured way, even as a property of VmException object?

**Comment by fmoletta** [comment]
Hello! 
In [cairo-rs-py](https://github.com/lambdaclass/cairo-rs-py) we are now returning a VmException when a vm run fails. Similarly to the original vm, it contains an `inner_exc `field with the error returned by the python interpreter in case of an exception inside a hint. For errors ocurring in the vm's code, the `inner_exc` will differ as they are still rust errors.
In cairo-rs we have a similar behaviour, but as hints are actually static rust code, the `inner_exc` is always a VirtualMachineError, and there is no "original exception" to pickle, so the errors will differ from python exceptions.
Hope this is helpful!
