### ISSUE TITLE
Error storing casted pointer

### ISSUE THREAD

**Issue by greged93** [lambdaclass/cairo-rs#679]
**Describe the bug**
The below compiled code produces a `ExpectedInteger` error when ran with the cairo-rs-run executable. However, running the same code with `cairo-run` works fine.

**To Reproduce**
1. Compile the below Cairo code with `cairo-compile main.cairo --output compiled.json`
2. Run the code with `cairo-run --program compiled.json --layout all`
3. Run the same compiled Cairo code with `target/release/cairo-rs-run path/to/compiled/file/compiled.json --layout all`
4. Should get an `VmException` caused by a `ExpectedInteger` on line 19.

**Expected behavior**
Expected cairo-rs-run to execute the program in the same way as `cairo-run`

**Additional context**
Cairo-lang version: 0.10.2
Cairo-rs: commit 5373211
Test code: 
```
from starkware.cairo.common.dict_access import DictAccess
from starkware.cairo.common.alloc import alloc
from starkware.cairo.common.default_dict import default_dict_new, default_dict_finalize
from starkware.cairo.common.dict import dict_write, dict_read

struct Structure {
    one: felt,
    two: felt,
    three: felt,
}

func main() {
    let (dictionary: DictAccess*) = default_dict_new(default_value=0);
    let (s: Structure*) = alloc();

    assert s[0] = Structure(1, 2, 3);
    tempvar ptr = cast(s, felt);

    dict_write{dict_ptr=dictionary}(key=0, new_value=ptr);
    return ();
}

```

**Comment by fmoletta** [comment]
Hello! Thanks for opening this issue!
We have identified the cause and are currently working on fixing this bug

**Comment by greged93** [comment]
Thank you for your work !
