### ISSUE TITLE
Two python environments are setup by `make deps`

### ISSUE THREAD

**Issue by ptisserand** [lambdaclass/cairo-rs#688]
**Describe the bug**
When running `make deps` two different virtual environment are setup.

**To Reproduce**
1. Go to project top directory
2. Run `make deps`

**Expected behavior**
I expect only one python environment to be setup

**Additional context**
https://github.com/lambdaclass/cairo-rs/blob/e29e000471316ca6ea55134702f581951f69baeb/Makefile#L77-L86

**Comment by martinacantaro** [comment]
Hi @ptisserand thank you for reporting. We will tackle this as part of this ticket: https://github.com/lambdaclass/cairo-rs/issues/713. I think there's a specific purpose for each of the environments but it's not clear what this purpose is. We'll look into it.

**Comment by Oppen** [comment]
These environments are there mainly to ease the speed comparisons with cairo-lang. We compare both with it running on CPython and on PyPy.
In any case, those envs use outdated interpreters, 3.9.x should be installed.
