### ISSUE TITLE
Getter for current_step in VM

### ISSUE THREAD

**Issue by hurrikaanig** [lambdaclass/cairo-rs#691]
I am currently working on this issue on cairo-foundry: https://github.com/open-dust/cairo-foundry/issues/43
It involves reading value of current_step in vm_core::VirtualMachine. But current_step is only visible in the crate so I can't access it from outside.

Would it be ok to make a getter for it or maybe make it public ? I'm not sure if that would bring any new issue.

**Comment by Oppen** [comment]
I see this has been fixed a while ago :)
Closing.
