### ISSUE TITLE
cairo-vm v0.1.1 breaks starkware's cairo-lang-casm v0.1.0 crate

### ISSUE THREAD

**Issue by CHr15F0x** [lambdaclass/cairo-rs#730]
**Describe the bug**
When using [cairo-lang-starknet](https://github.com/starkware-libs/cairo) as a dependency in your own Rust crate it turns out that [cairo-lang-casm](https://crates.io/crates/cairo-lang-casm) does not build.
The problem stems from the fact that `cairo-*` crates depend at a workspace level on
```toml=
cairo-vm = "0.1.0"
```
which means that all `cairo-vm` versions from the range `>= 0.1.0 && <0.2.0` [are valid here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).
Unfortunately `cairo-vm ` version `0.1.1` introduces breaking changes and thus `cairo-lang-starknet` (among others) fails to build.

**To Reproduce**
```
cargo new --lib example
cd example/
cargo add cairo-lang-starknet
cargo check 
```
Cargo check fails.

**Expected behavior**
Cargo check passes.

**Additional context**
I imagine that `cairo-vm 0.1.1` could be for yanked and re-released as `0.2.0` on crates.io which would fix all depending crates that use the `cairo-vm = "0.1.0"` dependency.
Right now I am using a fork of [cairo](https://github.com/eqlabs/cairo/tree/force-cairo-vm-0.1.0) which forces `"=0.1.0"` for `cairo-vm`.

**Comment by Juan-M-V** [comment]
Hi @CHr15F0x, we are working on a better fix for this issue. For now your fix seems like the best option. We are going to update the [README](https://github.com/lambdaclass/cairo-rs/pull/746) to include this!
