### ISSUE TITLE
Optimize property tests for felts 

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/cairo-rs#739]
The way the property tests generate random numbers right now is using this regex: `"(0|[1-9][0-9]*)"`

This has a 50% chance of outputting `0` (and 50% chance of outputting a random-length number that doesn't begin with 0). This makes for a lot of redundant tests where all of the variables are equal to 0.

So for example in a test with two variables x and y, we would use a unit test to cover the case where `x = 0, y = 0`.

And for property tests, we would require for at least one variable to be different from 0.

Tagging @juanbono because this came up in a discussion we had.

**Comment by martinacantaro** [comment]
Check also the typo in bitwise operation tests
>   // Checks that the result of perfforming a bit and operation between zeroes is zero

**Comment by Oppen** [comment]
Fixed a few weeks ago.
