### ISSUE TITLE
Implement `CheckedSub<usize>` for `Relocatable`

### ISSUE THREAD

**Issue by Juan-M-V** [lambdaclass/cairo-rs#748]
**Is your feature request related to a problem? Please describe.**
The current implementation of the `Relocatable` type has a method called [`sub_usize`](https://github.com/lambdaclass/cairo-rs/blob/75bfba3850194a270d270e80ea57d39235690edd/src/types/relocatable.rs#L152-L159) that could be replaced by a trait. 

**Describe the solution you'd like**
Instead of having a method in the type, the `ChekedSub` trait from the `num_traits` crate could be used. Something to keep in mind is that `sub_usize` returns a `Result` while `CheckedSub` returns an `Option`

**Additional context**
https://docs.rs/num-traits/latest/num_traits/ops/checked/trait.CheckedSub.html

**Comment by 0xNonCents** [comment]
I'll investigate this one.

**Comment by 0xNonCents** [comment]
I am seeing that the CheckedSub trait expects the RHS type to be the same as the LHS. I think we want the RHS to be different than `Relocatable` Perhaps we can implement the Sub<usize> trait instead?

**Comment by Juan-M-V** [comment]
Hm, that's a problem. The issue is that the method can fail and the Sub trait can't. I can't really think of a solution right now, I need to look into it a bit more to find a cleaner solution
