### ISSUE TITLE
Increase test coverage of Keccak builtin

### ISSUE THREAD

**Issue by Jrigada** [lambdaclass/cairo-rs#749]
**Is your feature request related to a problem? Please describe.**
Right now Keccak builtin is not as tested as the other builtins. 

**Describe the solution you'd like**
We should add more unit tests to test every function in the module

file: `src/vm/runners/builtin_runner/keccak.rs`

**Comment by 0xNonCents** [comment]
I'll take a look.

**Comment by 0xNonCents** [comment]
PR created https://github.com/lambdaclass/cairo-rs/pull/765
