### ISSUE TITLE
Rustdoc documentation

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo-rs#75]
- The rustdoc comments should be polished and expanded in general.
- cleopatra is yet green to publish to crate.io and thus docs.rs but perhaps work could be done on the CI to add the rendered docs to the repo's github pages.

**Comment by PartyLich** [comment]
> ... work could be done on the CI to add the rendered docs to the repo's github pages.

Are you accepting PRs for this?

If so, there's a working example in my fork. The [bench page](https://partylich.github.io/cleopatra_cairo/) remains the root, and has an additional link to the [docs](https://partylich.github.io/cleopatra_cairo/cleopatra_cairo/index.html).

**Comment by pefontana** [comment]
Already done
