### ISSUE TITLE
Extensible VirtualMachineError

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-rs#751]
[We](https://github.com/open-dust/cairo-foundry) are using cairo-rs to build a cairo testing suite. 
We are extending the VM with custom behaviors using hints (and other stuff).
We would like to be able to have our custom logic return specific custom VirtualMachineError.

Right now the only way to do so is to use the `VirtualMachineError::CustomHint(String)` variant.
Problem: 
- it only take a String, no custom error types
- for our "other stuff" that are not hints it's a smell to use something called `CustomHint`, yet it's the only thing we have now.

Our ideal implementation would be something like this:
`VirtualMachineError::Other(Box<dyn Error>)` or `VirtualMachineError::Other(anyhow::Error)` (if you don't mind the dependency)

If the lambdaclass team agrees, we can come up with a PR for this.

**Comment by unbalancedparentheses** [comment]
Hey this is great. Let me check with the team but I'm pretty we would love to have this.

**Comment by tdelabro** [comment]
@unbalancedparentheses you got time to talk about it?

**Comment by hurrikaanig** [comment]
Hey, I have talked with @tdelabro, I will be working on this :)
