### ISSUE TITLE
Missing Functions for ExecutionResources structure 

### ISSUE THREAD

**Issue by mmsc2** [lambdaclass/cairo-rs#767]
**Is your feature request related to a problem? Please describe.**
Current implementation of ExecutionResources is missing the functionalities it has in Python and are required in starknet-rs.

**Describe the solution you'd like**
It would be useful to replicate this functions to avoid implementing them outside of cairo-rs as ad doc solutions. 

**Additional context**
https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/vm/cairo_pie.py#L123

**Comment by 0xNonCents** [comment]
Ill take a look

**Comment by mmsc2** [comment]
> Ill take a look. Does starknet-rs or other projects have a currently operation ad hoc solution?

yes! here there is an example of and ad doc solution for __add__ functionality.

**Comment by mmsc2** [comment]
> Ill take a look. Does starknet-rs or other projects have a currently operation ad hoc solution?

yes! here is an example of two ad doc solutions for the `__add__`  and `filter_unused_builtins` functionalities 
https://github.com/lambdaclass/starknet_in_rust/pull/85/files#diff-65366c97240a497070bca37610a9c4fd70d0919c9a5b0d574f03cdefa4328ca8R56

the idea would be to replicate all the functions in the ExecutionResources class, mainly de __add__, __mul__ , __sub__ operations in order for us to be able to do something like 

``` rust
     let resources1 = ExecutionResources::{
        ..Default::default()
      }
     let resources2 = ExecutionResources::{
        ..Default::default()
      }
      
      resources1 + resources2
```

**Comment by 0xNonCents** [comment]
Cool. That makes sense. I am looking at how `builtin_instance_counter` is changed between the ops right now.
