### ISSUE TITLE
Implement the Display trait for the Instruction struct

### ISSUE THREAD

**Issue by Jrigada** [lambdaclass/cairo-rs#800]
**Is your feature request related to a problem? Please describe.**
Like what happens with the Memory struct we sometimes want to print the instruction in order to debug the VM and right now this is really hard to understand with the current format. 

**Describe the solution you'd like**
We should implement the Display trait for it to make it a little bit clearer to understand the fields inside the struct.

**Comment by chirag-bgh** [comment]
I would like to take this on

**Comment by pefontana** [comment]
Not necessary
