### ISSUE TITLE
Implement from_bytes_le operation inside the felt module for bigint_felt 

### ISSUE THREAD

**Issue by Jrigada** [lambdaclass/cairo-rs#801]
**Is your feature request related to a problem? Please describe.**
The transformation from little endian bytes to felt is missing right now. 

**Describe the solution you'd like**
We should have the ability to create a felt from the collection of little endian bytes.

**Comment by PatStiles** [comment]
Willing to take this on

**Comment by haroune-mohammedi** [comment]
I'd like to work on it, should I open a pull request or wait for someone to assign it to me ? Of course if @PatStiles didn't get assigned or working on it yet
