### ISSUE TITLE
Implement from_bytes_be operation inside the felt module for bigint_felt

### ISSUE THREAD

**Issue by Jrigada** [lambdaclass/cairo-rs#802]
**Is your feature request related to a problem? Please describe.**
The transformation from big endian bytes to felt is missing right now.

**Describe the solution you'd like**
We should have the ability to create a felt from the collection of big endian bytes.

**Comment by martinacantaro** [comment]
On it

**Comment by martinacantaro** [comment]
Clarification question:
The function that should be implemented for bigint_felts is the one from the BigInt crate? 
https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#method.from_bytes_be

**Comment by martinacantaro** [comment]
It appears the from_bytes_be operation is already implemented for felts and bigint felts. 

felt/src/lib.rs

```
impl Felt {
// --snip--  
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        Self {
            value: FeltBigInt::from_bytes_be(bytes),
        }
    }
```

felt/src/bigint_felt.rs

```
impl FeltOps for FeltBigInt<FIELD_HIGH, FIELD_LOW> {
// --snip--
    fn from_bytes_be(bytes: &[u8]) -> FeltBigInt<FIELD_HIGH, FIELD_LOW> {
        let mut value = BigUint::from_bytes_be(bytes);
        if value >= *CAIRO_PRIME {
            value = value.mod_floor(&CAIRO_PRIME);
        }
        Self::from(value)
    }
```

Both are also tested.
Is anything else needed?

PS: apparently, the test `from_bytes_be` in bigint_felt.rs would break in Cairo, as parsing the bytes for `b"Hello world!"` does not equal `b"22405534230753963835153736737"`
