### ISSUE TITLE
Increase unit test coverage in bigint_felt.rs

### ISSUE THREAD

**Issue by Jrigada** [lambdaclass/cairo-rs#803]
**Is your feature request related to a problem? Please describe.**
Right now the felt implementation is poorly tested

**Describe the solution you'd like**
It should reach a higher level of coverage than right now. 

- [x] Sum, 
- [x] Add, 
  - [x] Add zeros
- [x] AddAssign, 
  - [x] AddAssign zeros, 
- [x] BitAnd, 
- [x] BitOr, 
- [x] BitXor, 
- [x] Div, 
- [x] Mul, 
- [x] MulAssign, 
- [x] Neg, 
- [x] Rem, 
- [x] Shl, 
- [x] Shr, 
- [x] ShrAssign, 
- [x] Sub, 
- [x] SubAssign

**Comment by martinacantaro** [comment]
On it.

**Comment by martinacantaro** [comment]
- [ ] Sum, 
- [ ] Add, 
  - [ ] Add zeros
- [ ] AddAssign, 
- [ ] BitAnd, 
- [ ] BitOr, 
- [ ] BitXor, 
- [ ] Div, 
- [ ] Mul, 
- [ ] MulAssign, 
- [ ] Neg, 
- [ ] Rem, 
- [ ] Shl, 
- [ ] Shr, 
- [ ] ShrAssign, 
- [ ] Sub, 
- [ ] SubAssign

**Comment by martinacantaro** [comment]
I need to check if I'm doing zeros right when testing.

I'm doing
FeltBigInt::<FIELD_HIGH, FIELD_LOW>::new(0);

but maybe I need to do

FeltBigInt::zero
