### ISSUE TITLE
Benchmarks depends on `valgrind`

### ISSUE THREAD

**Issue by oboulant** [lambdaclass/cairo-rs#806]
# What happens

`make bench` needs `valgrind` to be installed. 

See console output :
```bash
Benchmarking cairo_run(cairo_programs/benchmarks/set_integration_benchmark.json                                                                               Benchmarking cairo_run(cairo_programs/benchmarks/set_integration_benchmark.json                                                                               Benchmarking cairo_run(cairo_programs/benchmarks/set_integration_benchmark.json                                                                               cairo_run(cairo_programs/benchmarks/set_integration_benchmark.json
                        time:   [668.90 ns 670.53 ns 672.38 ns]
Found 14 outliers among 100 measurements (14.00%)
  8 (8.00%) high mild
  6 (6.00%) high severe

     Running bench/iai_benchmark.rs (target/release/deps/iai_benchmark-291723aad0ed97f3)
Unexpected error while launching valgrind. Error: No such file or directory (os error 2)
```

# Corrective action

Maybe update the benchmark section of the global readme with a mention on the valgrind dependency and a link to where it can be found ? https://valgrind.org/downloads/current.html

**Comment by Oppen** [comment]
Updating the README is the correct solution. It shouldn't point to the site tho, but tell how to install, since it only runs on Unix compatible systems and all of them are typically used with package managers.
Regardless, I think there's a way to disable iai by default, it's there for the CI only.
