### ISSUE TITLE
`make test` needs cargo-llvm-cov

### ISSUE THREAD

**Issue by oboulant** [lambdaclass/cairo-rs#807]
# What happens 

`make test` needs `cargo-llvm-cov` to run. See console output : 
```bash
cargo llvm-cov nextest --no-report --workspace --features test_utils
error: no such command: `llvm-cov`

        View all installed commands with `cargo --list`
make: *** [test] Error 101
```

# Corrective action

## Change the docs

Maybe just change the "Testing" section of the global readme with a mention that one might need to run `make deps` before running her first `make test`. 

## Change the Makefile

Maybe make the `test` rule of the Makefile depends on the `deps` rule. Nevertheless, might be cumbersome to run the `deps` rule every time... 

## `cargo.toml` ?

New to rust, but is there a possibility to explicit dev dependencies in the `cargo.toml` ? https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies 
This would install dependencies once and for all at `cargo build` time. 
But again, may be off topic here : new to rust (and willing to learn :) )

**Comment by Oppen** [comment]
There is the option of specifying dev dependencies for dev __builds__, but I'm not sure you can cover the toolchain parts. I'll have to update the `Makefile` to include `cargo-llvm-cov` in the `deps` target.

**Comment by oboulant** [comment]
Closing since addressed in https://github.com/lambdaclass/cairo-rs/pull/809
