### ISSUE TITLE
Add tests for num_traits for Felts

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/cairo-rs#823]
Add tests for num_traits for Felts:
- [x] Bounded
- [x] FromPrimitive
- [ ] Num
- [ ] One
- [x] Pow
- [ ] Signed
- [x] ToPrimitive
- [ ] Zero

**Comment by PatStiles** [comment]
Willing to take this on!

**Comment by oboulant** [comment]
Sorry @PatStiles : did not reloaded the page before pushing tests for the Zero trait ! 
Please, feel free to take the rest of the traits and even propose a better alternative to what I wrote in here : https://github.com/lambdaclass/cairo-rs/pull/831

**Comment by haroune-mohammedi** [comment]
@PatStiles are you working on this ? If not, I'm willing to step up and take it
