### ISSUE TITLE
`PartialEq` implemented on error types

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-rs#877]
As explained here: https://github.com/lambdaclass/cairo-rs/pull/776#issuecomment-1406281788, error types should not implement `Eq` or `PartialEq`. It does not make sense and is only used during testing, never during the actual execution. We should use [`assert_matches`](https://crates.io/crates/assert_matches) instead while testing.

Some error types in the codebase have been reworked to eliminate this, but I saw that some others were still using it and that new error types (`MathError`) were being added with the `PartialEq` derived.

Do you want an OnlyDust contributor to work on removing `PartialEq` from the last types it has been implemented on, and rewrite the related tests assertions?

**Comment by tdelabro** [comment]
@fmoletta wdyt ?

**Comment by fmoletta** [comment]
I don't think it's something needed at the moment.
