### ISSUE TITLE
Derive Deserialize on Program

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-rs#895]
```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Program {
    pub builtins: Vec<&'static str>,
    ...
}
```

Recently the `builtins` field of the `Program` struct changed from `Vec<String>` to `Vec<&'static str>`. This makes sense because it's always populated with values coming from this function:

```rust
impl BuiltinName {
    pub fn name(&self) -> &'static str {
        match self {
            BuiltinName::output => OUTPUT_BUILTIN_NAME,
            BuiltinName::range_check => RANGE_CHECK_BUILTIN_NAME,
            BuiltinName::pedersen => HASH_BUILTIN_NAME,
            BuiltinName::ecdsa => SIGNATURE_BUILTIN_NAME,
            BuiltinName::keccak => KECCAK_BUILTIN_NAME,
            BuiltinName::bitwise => BITWISE_BUILTIN_NAME,
            BuiltinName::ec_op => EC_OP_BUILTIN_NAME,
        }
    }
}
```

In starknet_in_rust, it is used in the struct `ContractClass` upon which the trait Deserialize is derived. It was not a problem when the builtins were `Vec<String>` but it becomes one when they are references with static lifetime, because if we just derive `Deserialize`, it is expected that the whole object from which we are reading is static too.
We could introduce a named lifetime instead of using `'static`, but it would make it impossible to use on an object that does not outlive the resulting struct, which is already happening in a lot of places:
```rust
trait Storage {
 fn get_value(&self, key: &StorageKey) -> Option<Vec<u8>>;

 fn get_contract_state(&self, key: &[u8; 32]) -> Result<ContractState, StorageError> {
        let ser_contract_state = self
            .get_value(&(Prefix::ContractState, *key))
            .ok_or(StorageError::ErrorFetchingData)?;

        let contract_state: ContractState = serde_json::from_slice(&ser_contract_state)?;
        Ok(contract_state)
    }
}
```

We can solve this in different ways.

The first one is to use a custom function to deserialize this field rather that the default one shipped by the trait derivation. It may look like this:
```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Program {
    #[serde(deserialize_with = "deserialize_builtins")]
    pub builtins: Vec<&'static str>,
    ...
}


fn deserialize_builtins<'de, D>(data: D) -> Result<Vec<&'static str>, D::Error>
where
    D: Deserializer<'de>,
{
    struct BuiltinsVisitor;

    impl<'de> Visitor<'de> for BuiltinsVisitor {
        type Value = Vec<&'static str>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a string containing json data")
        }

        fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
        where
            E: serde::de::Error,
        {
            let builtins =
                serde_json::from_str(v)
                    .map_err(E::custom)
                    .map(|builtins: Vec<String>| {
                        builtins
                            .iter()
                            .map(|builtin| match builtin.as_str() {
                                OUTPUT_BUILTIN_NAME => Ok(OUTPUT_BUILTIN_NAME),
                                RANGE_CHECK_BUILTIN_NAME => Ok(RANGE_CHECK_BUILTIN_NAME),
                                HASH_BUILTIN_NAME => Ok(HASH_BUILTIN_NAME),
                                SIGNATURE_BUILTIN_NAME => Ok(SIGNATURE_BUILTIN_NAME),
                                KECCAK_BUILTIN_NAME => Ok(KECCAK_BUILTIN_NAME),
                                BITWISE_BUILTIN_NAME => Ok(BITWISE_BUILTIN_NAME),
                                EC_OP_BUILTIN_NAME => Ok(EC_OP_BUILTIN_NAME),
                                _ => return Err(E::custom("unknown builtin")),
                            })
                            .collect::<Result<Vec<&'static str>, E>>()
                    })??;

            Ok(builtins)
        }
    }

    data.deserialize_any(BuiltinsVisitor)
}
```    
It should work, but look rather silly. Not gonna lie.

Another way would be to use an enum like `BuiltinName`, rather than a raw string. It will have better performance, be a more expressive type and solve our lifetime problems.
Here is a commit that does more or less this on my fork: https://github.com/open-dust/cairo-rs/commit/4f1a2096f4d6001ad1dd6ab85f4ad4dc65c233df
The only thing I'm not sure is about supporting other custom built-ins. Is it something that is needed? I'm under the impression it is needed because there is an `add_additional_hash_builtin` in the codebase, which does exactly that. My opinion is that we can still make it possible by adding an escape variant to the enum, something like `Other(String)`. 

In the same vein, we can just revert to `Vec<String>`, but I think having an enum brings additional value.

I hope it gave you a clear view of what is the problem, and that my ideas of solutions can help. I will be glad to help further, maybe making the PR once we agreed on the best way to do this.

**Comment by fmoletta** [comment]
Hello! May I propose a third simple solution?
We could use the `BuiltinName` enum on the `Program` struct, and then convert these to `&'satic str` when storing the builtins in the `VirtualMachine`. This would require the minimum changes to the code.

**Comment by tdelabro** [comment]
Hey.
Why is it better to have `&'static str` on the `VirtualMachine`?

What about the escape variant? Is it needed? Do you agree with the proposition I did?

**Comment by fmoletta** [comment]
I wouldn't say its better or worse, it's just less changes to the code & public api. 
Regarding the escape variant, it would be needed if `BuiltinName` were to be used in the `builtin_runners` field of the `VirtualMachine`, but it would defeat the purpose of the `BuiltinName` enum, which is to check for invalid builtin names at deserialization time

**Comment by tdelabro** [comment]
Ok I understand. I will do a PR with what you suggested :)
