### ISSUE TITLE
[New Hints] ec_bigint.json

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-rs#975]
Implement the remaining hints in ec_bigint.json

 ## NewHint#35

Assigned:
Status: todo

```python
from starkware.cairo.common.cairo_secp.secp_utils import pack
from starkware.cairo.common.math_utils import as_int
from starkware.python.math_utils import div_mod, safe_div

p = pack(ids.P, PRIME)
x = pack(ids.x, PRIME) + as_int(ids.x.d3, PRIME) * ids.BASE ** 3 + as_int(ids.x.d4, PRIME) * ids.BASE ** 4
y = pack(ids.y, PRIME)

value = res = div_mod(x, y, p)
```

 ## NewHint#36

Assigned:
Status: todo

```python
k = safe_div(res * y - x, p)
value = k if k > 0 else 0 - k
ids.flag = 1 if k > 0 else 0
```

**Comment by jpcenteno** [comment]
Corporate needs you to find the differences between hint 35 and hint 36.

![image](https://user-images.githubusercontent.com/14025793/233444737-de2d638d-ad0d-4d65-bcbe-09b60d3ed213.png)

**Comment by jpcenteno** [comment]
I fixed the issue description with the correct value for the  **NewHint#36**. Got confirmation from @pefontana
